### ISSUE TITLE
Bazaar extension list looping

### ISSUE THREAD

**Issue by Patbox** [flagrow/bazaar#130] opened 2019-02-23 13:50 UTC
### Steps to reproduce

1. Go to Bazaar
2. Click More, load

### Expected behaviour

Load more extensions

### Actual behaviour

Loops visible extensions

https://youtu.be/qNwvvJna9LY
### Configuration

**Operating system:** Ubuntu 16.04 Server

**Version of Bazaar:** 0.3.9
**Version of Flarum:** Beta 8.1
**Other extensions:** 
+---------------------------------+-----------------+--------+
| flarum-approval                 | v0.1.0-beta.8   |        |
| flarum-bbcode                   | v0.1.0-beta.8   |        |
| flarum-emoji                    | v0.1.0-beta.8   |        |
| flagrow-console                 | 0.4.3           |        |
| flarum-flags                    | v0.1.0-beta.8.1 |        |
| flarum-likes                    | v0.1.0-beta.8.1 |        |
| flarum-lock                     | v0.1.0-beta.8   |        |
| flarum-markdown                 | v0.1.0-beta.8   |        |
| flarum-mentions                 | v0.1.0-beta.8.1 |        |
| flarum-sticky                   | v0.1.0-beta.8   |        |
| flarum-subscriptions            | v0.1.0-beta.8   |        |
| flarum-suspend                  | v0.1.0-beta.8   |        |
| flarum-tags                     | v0.1.0-beta.8.2 |        |
| flarum-auth-facebook            | v0.1.0-beta.8   |        |
| fof-secure-https                | v0.1.0          |        |
| fof-user-bio                    | 0.1.2           |        |
| flagrow-linguist                | 0.3.0           |        |
| reflar-reactions                | 1.0.0-beta.5.1  |        |
| flagrow-split                   | 0.3.2           |        |
| michaelbelgium-discussion-views | v0.1.0-beta.8   |        |
| fof-pages                       | 0.1.2           |        |
| reflar-nightmode                | 0.2.0           |        |
| wiwatsrt-best-answer            | v0.2.0          |        |
| flarum-auth-github              | v0.1.0-beta.8   |        |
| fof-links                       | 0.1.1           |        |
| fof-transliterator              | 0.1.1           |        |
| flarum-statistics               | v0.1.0-beta.8   |        |
| reflar-webhooks                 | 0.1.6           |        |
| matteocontrini-imgur-upload     | v3.2.0          |        |
| fof-formatting                  | 0.1.2           |        |
| fof-bbcode-details              | 0.1.0           |        |
| bepro-lang-polish               | 0.8.1.0         |        |
| flarum-pusher                   | v0.1.0-beta.8.1 |        |
| flagrow-byobu                   | 0.2.2           |        |
| flarum-lang-english             | v0.1.0-beta.8   |        |
| reflar-polls                    | 1.3.2           |        |
| flagrow-direct-links            | 0.2.0           |        |
| v17development-seo              | 0.3-beta        |        |
| flagrow-sitemap                 | 0.2.0           |        |
| flagrow-bazaar                  | 0.3.9           |        |
| flarum-auth-twitter             | v0.1.0-beta.8   |        |
+---------------------------------+-----------------+--------+

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by luceos** [comment] 2019-02-23 20:42
I was able to confirm this. Thank you for reporting, I'll look into this asap.

**Comment by luceos** [comment] 2019-02-23 21:39
If you're able feel free to give dev-master a spin. I'll do a second test beginning of the week and then tag a new version.

**Comment by PCTipsGR** [comment] 2019-04-21 20:14
I have the exact same error, using the same version of Bazaar. Can't use the dev branch at the moment because I don't have Composer.
Any updates on this? Sorry for bumping.

**Comment by clarkwinkelmann** [comment] 2019-04-25 19:55
Confirmed fixed in dev-master. A new release will be tagged in a few minutes

**Closed by clarkwinkelmann** 2019-04-25 19:55 UTC
