### ISSUE TITLE
Cannot install or remove extensions

### ISSUE THREAD

**Issue by benhartwich** [flagrow/bazaar#100] opened 2017-12-08 21:20 UTC
### Steps to reproduce

1. Install flarum
2.  install your bazar extension
3.  try to install another extension

### Expected behaviour

The other extension should be installed via bazar backend management.

### Actual behaviour

I get an oops something went wrong error

### Configuration

**Operating system:**  Debian 8

**Version of Bazaar:** latest
**Version of Flarum:** latest
**Other extensions:** 
Flarum core 0.1.0-beta.7
PHP 7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
EXT flagrow-analytics 0.6.0
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT wiwatsrt-best-answer v0.1.0-beta.11
EXT davis-customfooter v0.1.0-beta4
EXT cbmainz-de 0.7.1
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flarum-auth-facebook v0.1.0-beta.6
EXT flagrow-bazaar 0.2.4
EXT flagrow-upload 0.6.0
EXT flarum-flags v0.1.0-beta.7
EXT avatar4eg-geotags 0.2.0
EXT sijad-recaptcha 0.0.2
EXT flagrow-guardian 0.1.2
EXT flarum-likes v0.1.0-beta.6
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT s9e-mediaembed 0.3.2
EXT flarum-mentions v0.1.0-beta.7
EXT manelizzard-notify 0.2.1
EXT sijad-pages 0.1.0-beta.3
EXT avatar4eg-share-social 0.2.3
EXT xengine-signature 0.1.2
EXT terabin-sitemap v1.0.2-beta.2
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT jordanjay29-summaries 0.2.0
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: https://astronomie.community
Installation path: /var/kunden/flarum/httpdocs

<details><summary>**Logs**:</summary>
POST https://astronomie.community/api/bazaar/extensions

{
  "errors": [
    {
      "code": 500,
      "title": "Internal server error",
      "detail": "Flagrow\\Bazaar\\Exceptions\\ComposerException: <error>Your requirements could not be resolved to an installable set of packages.</error> in /var/kunden/flarum/httpdocs/vendor/flagrow/bazaar/src/Composer/Utils/ComposerIO.php:17\nStack trace:\n#0 /var/kunden/flarum/httpdocs/vendor/composer/composer/src/Composer/Installer.php(474): Flagrow\\Bazaar\\Composer\\Utils\\ComposerIO->writeError('<error>Your req...', true, 1)\n#1 /var/kunden/flarum/httpdocs/vendor/composer/composer/src/Composer/Installer.php(226): Composer\\Installer->doInstall(Object(Composer\\Repository\\InstalledFilesystemRepository), Object(Composer\\Repository\\CompositeRepository), Object(Composer\\Repository\\PlatformRepository), Array)\n#2 /var/kunden/flarum/httpdocs/vendor/flagrow/bazaar/src/Composer/Commands/BaseCommand.php(113): Composer\\Installer->run()\n#3 /var/kunden/flarum/httpdocs/vendor/flagrow/bazaar/src/Composer/ComposerCommand.php(31): Flagrow\\Bazaar\\Composer\\Commands\\BaseCommand->run(Array)\n#4 /var/kunden/flarum/httpdocs/vendor/flagrow/bazaar/src/Jobs/RequirePackage.php(15): Flagrow\\Bazaar\\Composer\\ComposerCommand->requires('datitisev/flaru...')\n#5 /var/kunden/flarum/httpdocs/vendor/flagrow/bazaar/src/Jobs/ComposerJob.php(62): Flagrow\\Bazaar\\Jobs\\RequirePackage->handleComposer(Object(Flagrow\\Bazaar\\Composer\\ComposerCommand), Object(Flagrow\\Bazaar\\Models\\Task))\n#6 /var/kunden/flarum/httpdocs/vendor/flagrow/bazaar/src/Jobs/ComposerJob.php(100): Flagrow\\Bazaar\\Jobs\\ComposerJob->handle(Object(Flagrow\\Bazaar\\Composer\\ComposerEnvironment), Object(Monolog\\Logger))\n#7 /var/kunden/flarum/httpdocs/vendor/flagrow/bazaar/src/Extensions/PackageManager.php(51): Flagrow\\Bazaar\\Jobs\\ComposerJob::launchJob(Object(Flagrow\\Bazaar\\Models\\Task))\n#8 /var/kunden/flarum/httpdocs/vendor/flagrow/bazaar/src/Repositories/ExtensionRepository.php(202): Flagrow\\Bazaar\\Extensions\\PackageManager->requirePackage('datitisev/flaru...')\n#9 /var/kunden/flarum/httpdocs/vendor/flagrow/bazaar/src/Api/Controllers/InstallExtensionController.php(49): Flagrow\\Bazaar\\Repositories\\ExtensionRepository->installExtension('datitisev/flaru...')\n#10 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(97): Flagrow\\Bazaar\\Api\\Controllers\\InstallExtensionController->data(Object(Zend\\Stratigility\\Http\\Request), Object(Tobscure\\JsonApi\\Document))\n#11 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php(23): Flarum\\Api\\Controller\\AbstractSerializeController->handle(Object(Zend\\Stratigility\\Http\\Request))\n#12 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Http/Handler/ControllerRouteHandler.php(53): Flarum\\Api\\Controller\\AbstractCreateController->handle(Object(Zend\\Stratigility\\Http\\Request))\n#13 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(69): Flarum\\Http\\Handler\\ControllerRouteHandler->__invoke(Object(Zend\\Stratigility\\Http\\Request), Array)\n#14 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\DispatchRoute->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#15 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\DispatchRoute), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#16 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#17 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#18 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\SetLocale->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#19 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\SetLocale), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#20 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#21 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(58): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#22 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\AuthenticateWithHeader->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#23 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\AuthenticateWithHeader), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#24 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#25 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(36): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#26 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\AuthenticateWithSession->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#27 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\AuthenticateWithSession), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#28 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#29 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(39): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#30 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\RememberFromCookie->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#31 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\RememberFromCookie), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#32 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#33 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Http/Middleware/StartSession.php(48): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#34 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\StartSession->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#35 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\StartSession), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#36 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#37 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(33): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#38 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Api\\Middleware\\FakeHttpMethods->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#39 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Api\\Middleware\\FakeHttpMethods), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#40 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#41 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(31): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#42 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\ParseJsonBody->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#43 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\ParseJsonBody), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#44 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#45 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Api/Middleware/HandleErrors.php(45): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#46 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Api\\Middleware\\HandleErrors->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#47 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Api\\Middleware\\HandleErrors), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#48 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#49 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(111): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#50 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Http/AbstractServer.php(55): Zend\\Stratigility\\MiddlewarePipe->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\NoopFinalHandler))\n#51 /var/kunden/flarum/httpdocs/vendor/zendframework/zend-diactoros/src/Server.php(157): Flarum\\Http\\AbstractServer->__invoke(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Diactoros\\Response), Object(Zend\\Stratigility\\NoopFinalHandler))\n#52 /var/kunden/flarum/httpdocs/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\\Diactoros\\Server->listen(Object(Zend\\Stratigility\\NoopFinalHandler))\n#53 /var/kunden/flarum/httpdocs/api.php(16): Flarum\\Http\\AbstractServer->listen()\n#54 {main}"
    }
  ]
}
</details>

**Comment by luceos** [comment] 2017-12-11 13:43
Okay so the php flarum info output shows you have many other extensions installed, how did you install these? The issue you see is related to a requirement of one extension, which one depends on the extensions you have installed and the extension you tried installing. Could you be more specific on how to reproduce this state?

**Comment by benhartwich** [comment] 2017-12-11 13:45
Hi,

I´ve installed the the extensions by using command line: sudo -u flarum composer require...
All files are owned by flarum. How can I give you further debugging infos? 

Currently I can´t use the bazaar app anymore because I get a 504 error. Php memory has 1G.

**Comment by luceos** [comment] 2017-12-11 13:48
Okay so you explain that to reproduce I can install Flarum, then Bazaar and then any extension via Bazaar. But your `php flarum info` output lists these installed extensions, eg:

- EXT jordanjay29-summaries 0.2.0
- EXT sijad-pages 0.1.0-beta.3
- EXT manelizzard-notify 0.2.1

and many more non-core extensions. My question is:

- How did you install these if you can't use Bazaar?
- Which extension did you install after which your Flarum install went broken?

Also please post your `composer.lock` file, please upload it as a file.

**Comment by benhartwich** [comment] 2017-12-11 13:56
I´ve installed flarum a while ago. Two days ago I configured it for the first time and installed different extension only via command line. After I had installed different extensions by command line I found your app for managing extensions. After I raised the php memory your extension worked for the first time, but installation or removing failed with the error code above.

To reproduce my problem:
- Install flarum
- Install different apps on command line
- activate the apps (on activation failure: set flarum to debug mode true)
- install bazaar, activate bazaar
- try to install or remove apps via bazaar.

Github doesn´t support this file type. You can download my file at https://cloud.speibox.de/s/Vq8g6vt6wQmZTPy

**Comment by luceos** [comment] 2017-12-11 15:19
Could you also share your `composer.json`, seems the lock by itself isn't enough 😞

**Comment by benhartwich** [comment] 2017-12-11 15:21
Of course: https://cloud.speibox.de/s/SAHSpgbHbJoDIJt

**Comment by luceos** [comment] 2017-12-11 19:40
What specific extension did you try to install with Bazaar. Because currently I can easily install your dependencies.

**Comment by benhartwich** [comment] 2017-12-11 20:18
I tried Dashboard. I don´t really know, what is / was causing the problem. For now it´s working again. Perhaps it´s a cache issue or could it be that your bazaar api key is limited for use of different site parallel? Could your api key have a time-out?

**Comment by benhartwich** [comment] 2017-12-11 20:28
When I get a 504 error (sometime when I load the bazaar admin page) I see at chrome developer console the following error:
admin-266f5493.js:17326 Uncaught TypeError: originalConfig.apply is not a function
    at Object.vdom.attrs.config (admin-266f5493.js:17326)
    at admin-266f5493.js:1167
    at admin-266f5493.js:2052
    at forEach (admin-266f5493.js:911)
    at Function.m.render (admin-266f5493.js:2052)
    at admin-266f5493.js:2254
    at forEach (admin-266f5493.js:911)
    at redraw (admin-266f5493.js:2250)

**Comment by luceos** [comment] 2017-12-12 07:00
I've been thinking about this issue and concluded the following;

- You have been able to access bazaar, while installing an extension it throws (correctly) a 500 explaining that your server requirements aren't met. This indicates that the installation halted halfway and nothing was installed, as such nothing happened that can break your forum.
- With the above being true you explain you have installed extensions previously and Flarum is now showing an error. 

Could you perhaps install a clean version with only Bazaar and see if that works? If so, we can exclude Bazaar as the culprit in your issue.

**Comment by benhartwich** [comment] 2017-12-12 07:49
I´ve installed a fresh flarum and installed your app by command line (composer require...)
On the first visit of bazaar I got an javascript error:
`TypeError: originalConfig.apply is not a function
[Weitere Informationen]
admin-2ea8ea7e.js:1930:81
render/vdom.attrs.config
http://test.astronomie.community/assets/admin-2ea8ea7e.js:1930:81
scheduleConfigsToBeCalled/<
http://test.astronomie.community/assets/admin-2ea8ea7e.js:163:32
m.render/<
http://test.astronomie.community/assets/admin-2ea8ea7e.js:327:34
forEach
http://test.astronomie.community/assets/admin-2ea8ea7e.js:94:54
m.render
http://test.astronomie.community/assets/admin-2ea8ea7e.js:327:1
redraw/<
http://test.astronomie.community/assets/admin-2ea8ea7e.js:399:1
forEach
http://test.astronomie.community/assets/admin-2ea8ea7e.js:94:54
redraw
http://test.astronomie.community/assets/admin-2ea8ea7e.js:397:1`

After reloading the page I could access bazaar. First I tried to install the Deutsch app. This failed with the same javascript error. Nginx log says: connection timed out. 
I use php 7.1 and my php settings are:
`php_admin_value[open_basedir] = /var/kunden/flarum:/usr/share/php:/tmp:/var/ngx_pagespeed_cache:/var/run/nginx/cache
php_admin_value[disable_functions] = dl,passthru,shell_exec,system,proc_open,popen,show_source
php_admin_value[memory_limit] = 1G
php_admin_value[max_execution_time] = 360
`
Nginx pagespeed is off, there is no opcache or fastcgi_cache.

**Comment by luceos** [comment] 2017-12-12 08:24
You should try using cronjob processing.

Update your bazaar constraint in your `composer.json` to match `dev-master` then run `composer update --prefer-dist --no-dev -o`. After that follow the instructions for cronjob processing, which will offload the request to nginx:

https://github.com/flagrow/bazaar/wiki/Cron-task-processing

**Comment by clarkwinkelmann** [comment] 2018-05-03 06:43
I'm closing this as it's been some time since the last activity.

Let us know if you experience this again :wink:

**Closed by clarkwinkelmann** 2018-05-03 06:43 UTC

**Comment by luceos** [comment] 2018-05-03 08:01
Please note the suggestion to use dev-master is no longer valid as that branch has been readied up for Flarum beta 8.
