### ISSUE TITLE
Failed to clone

### ISSUE THREAD

**Issue by SamB440** [flagrow/bazaar#75] opened 2017-07-31 10:22 UTC
Hi, I have an issue when trying to uninstall / install / update an extension. It seems that it tries to clone from github and fails.

### Steps to reproduce

1. Go to admin
2. Open bazaar tab
3. Try to uninstall / install / update and you will get this error

### Expected behaviour

It should update / install / uninstall.

### Actual behaviour

I get an error. Oops! Something went wrong. Please reload the page and try again. This happens on any extension. It doesn't even seem to be trying to clone from the extension I'm actually updating / installing / uninstalling.

### Configuration

**Version of Bazaar: 0.2.2** 
**Version of Flarum: Beta 6** 

<details><summary>**Logs**:</summary>
Failed to clone https://github.com/Cl1608Ho/flarum-ext-discord-webhook.git, git was not found, check that it is installed and in your PATH env.

sh: git: command not found

</details>

**Comment by clarkwinkelmann** [comment] 2017-08-01 17:03
Hi, thanks for your report.

Can you share the content of your `composer.json` file and your composer version (via `composer --version`) ?

**Comment by SamB440** [comment] 2017-08-01 19:00
Composer.json:
`{
    "name": "flarum/flarum",
    "description": "Delightfully simple forum software.",
    "type": "project",
    "keywords": ["forum", "discussion"],
    "homepage": "http://flarum.org",
    "license": "MIT",
    "authors": [
        {
            "name": "Toby Zerner",
            "email": "toby.zerner@gmail.com"
        },
        {
            "name": "Franz Liedke",
            "email": "franz@develophp.org"
        }
    ],
    "support": {
        "issues": "https://github.com/flarum/core/issues",
        "source": "https://github.com/flarum/flarum",
        "docs": "http://flarum.org/docs"
    },
    "require": {
        "flarum/core": "^0.1.0",
        "flarum/flarum-ext-akismet": "^0.1.0",
        "flarum/flarum-ext-approval": "^0.1.0",
        "flarum/flarum-ext-auth-facebook": "^0.1.0",
        "flarum/flarum-ext-auth-github": "^0.1.0",
        "flarum/flarum-ext-auth-twitter": "^0.1.0",
        "flarum/flarum-ext-bbcode": "^0.1.0",
        "flarum/flarum-ext-emoji": "^0.1.0",
        "flarum/flarum-ext-english": "^0.1.0",
        "flarum/flarum-ext-flags": "^0.1.0",
        "flarum/flarum-ext-likes": "^0.1.0",
        "flarum/flarum-ext-lock": "^0.1.0",
        "flarum/flarum-ext-markdown": "^0.1.0",
        "flarum/flarum-ext-mentions": "^0.1.0",
        "flarum/flarum-ext-pusher": "^0.1.0",
        "flarum/flarum-ext-sticky": "^0.1.0",
        "flarum/flarum-ext-subscriptions": "^0.1.0",
        "flarum/flarum-ext-suspend": "^0.1.0",
        "flarum/flarum-ext-tags": "^0.1.0",
        "flagrow/bazaar": "^0.1.0",
        "cl1608ho/flarum-ext-discord-webhook": "^0.1.0@beta",
        "flagrow/upload": "^0.5.7",
        "sijad/flarum-ext-links": "^0.1.0@beta",
        "xengine/flarum-ext-signature": "^0.1.2",
        "ganuonglachanh/flarum-ext-markdown-editor": "^0.9.0",
        "hugogit/flarum-ext-discordwidget": "^0.1.7",
        "flagrow/byobu": "^0.1.0@beta",
        "datitisev/flarum-ext-dashboard": "^0.1.0@beta",
        "jordanjay29/flarum-ext-summaries": "^0.2.0"
    },
    "require-dev": {
        "franzl/studio": "^0.11.0"
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "beta",
    "prefer-stable": true
}`
Composer version: 1.4.1

**Comment by luceos** [comment] 2017-08-01 19:32
@clarkwinkelmann i think the issue is that composer will fall back on doing a git checkout/clone in case no dist tarball was found. There might be several reasons for that, but none we have any influence on. I guess we need to start working on our own dist files directory. 😬

**Comment by clarkwinkelmann** [comment] 2017-08-02 17:06
> @luceos i think the issue is that composer will fall back on doing a git checkout/clone in case no dist tarball was found

That's what I believe as well.

@SamB440 I installed a Flarum just like yours based on the composer file and I can't reproduce the issue. This must be something with your environment.

I may suggest you try to clear composer cached files. A thing that happened to me in the past was the cache was written with wrong permissions and everytime composer ran it was fetching things again in a different manner.

> @luceos I guess we need to start working on our own dist files directory

Wouldn’t we end up hitting the same kind of issues with our own implementation ? :thinking:

**Comment by SamB440** [comment] 2017-08-02 18:57
I tried clearing the cache and the issue still occurs :(

**Comment by clarkwinkelmann** [comment] 2017-08-02 19:40
Seeing you have `"config": { "preferred-install": "dist" }` in your `composer.json` there's no reason for composer to try downloading the source code...

I'm running out of suggestions. If you are able to install `git` on your server, you could at least use Bazaar, even if it fetches the source instead of the dist.

**Comment by luceos** [comment] 2017-08-02 21:31
What composer version is installed @SamB440 ?

**Comment by SamB440** [comment] 2017-08-03 11:44
1.4.1, as stated before :P

**Comment by luceos** [comment] 2017-08-03 11:52
Sorry I missed that :grin: I also think your cache folder is not writable. Can you run the action bazaar tries manually?

```
composer require flagrow/upload -vvv
```

**Comment by clarkwinkelmann** [comment] 2017-08-21 22:33
@SamB440 is this still happening ? Did you try @luceos suggestion ?

I'm closing this because it's clearly not a Bazaar issue. Feel free to come back with additional information. I'll re-open if necessary :wink:

**Closed by clarkwinkelmann** 2017-08-21 22:33 UTC
